services:
  javaapp:
    build:
      context: .
      dockerfile: ./images/java/Dockerfile
    restart: always
    ports:
      - "127.0.0.1:8081:8081"
    command: java -jar app.jar

  php:
    build: ./images/php
    restart: always
    volumes:
      - ./www:/var/www
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8085:8085"
      - "443:443"
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./www:/var/www
      - ./logs:/var/log/nginx
    depends_on:
      - php
      - javaapp

  redis:
    image: redis:latest
    restart: always
    ports:
      - "127.0.0.1:6380:6379"
